### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wxli1988** [dankogai/js-deflate#11]
经过测试发现使用C#压缩的文本内容无法用其解压，这是为什么呢

**Comment by dankogai** [comment]
This is a javascript project.  What does C# have to do with it?

**Comment by wxli1988** [comment]
Because the text is compressed by C#, and we want to use the JS to extract it.You can understand Chinese, so great.

**Comment by wxli1988** [comment]
Thank you,I've got out of the trouble.
